function graficoPrev(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 12-Dec-2015 19:04:09

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'YTickLabel',{'0','6.000','12.000','18.000','21.000',''},...
    'YTick',[0 5000 10000 15000 20000 21000],...
    'YGrid','on',...
    'XTick',[0 200 400 600 800 1000 1200 1400 1600 1800 2000 2200 2400 2500],...
    'XGrid','on',...
    'Position',[0.0534429599177801 0.11 0.936279547790339 0.812829581993569]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 2500]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 21000]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'DisplayName','Dados reais');
set(plot1(2),'Color',[1 0 0],'DisplayName','Previsão');

% Create legend
legend(axes1,'show');

